name: Security
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
permissions:
  contents: read
  security-events: write
jobs:
  secret-scanning:
    name: Secret Scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: TruffleHog Secret Scan
        uses: trufflesecurity/trufflehog@v3.67.3
      - name: Upload Secret Scan Results
        uses: actions/upload-artifact@v4
        with:
          name: secret-scan-results
          path: secret-scan-results/
    timeout-minutes: 10
  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12.2336.0
        with:
          directory: .
      - name: Upload Static Analysis Results
        uses: actions/upload-artifact@v4
        with:
          name: static-analysis-results
          path: static-analysis-results/
    timeout-minutes: 10
